# Generated by Django 5.1.4 on 2024-12-13 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('race', models.TextField(blank=True, default='Human')),
                ('clazz', models.TextField(blank=True, choices=[(None, ''), ('A', 'Artificer'), ('B', 'Barbarian'), ('Bd', 'Bard'), ('C', 'Cleric'), ('D', 'Druid'), ('F', 'Fighter'), ('M', 'Monk'), ('P', 'Paladin'), ('R', 'Ranger'), ('Rg', 'Rogue'), ('S', 'Sorcerer'), ('W', 'Wizard')], null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField()),
                ('approved_users', models.ManyToManyField(related_name='campaign_users', to=settings.AUTH_USER_MODEL)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonPlayerCharacter',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.character')),
                ('hostility', models.TextField(choices=[('H', 'Hostile'), ('N', 'Neutral'), ('F', 'Friendly')], default='N')),
            ],
            bases=('core.character',),
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign'),
        ),
        migrations.AddField(
            model_name='character',
            name='related_characters',
            field=models.ManyToManyField(related_name='related_characters', to='core.character'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('hostility', models.TextField(choices=[('H', 'Hostile'), ('N', 'Neutral'), ('F', 'Friendly')], default='N')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('neighboring_locations', models.ManyToManyField(related_name='neighboring_locations', to='core.location')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('hostility', models.TextField(choices=[('H', 'Hostile'), ('N', 'Neutral'), ('F', 'Friendly')], default='N')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('related_organizations', models.ManyToManyField(related_name='related_organizations', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('clazz', models.TextField(blank=True, choices=[(None, ''), ('A', 'Artificer'), ('B', 'Barbarian'), ('Bd', 'Bard'), ('C', 'Cleric'), ('D', 'Druid'), ('F', 'Fighter'), ('M', 'Monk'), ('P', 'Paladin'), ('R', 'Ranger'), ('Rg', 'Rogue'), ('S', 'Sorcerer'), ('W', 'Wizard')], null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('hostility', models.TextField(blank=True, choices=[('H', 'Hostile'), ('N', 'Neutral'), ('F', 'Friendly')], default='N', null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('characters', models.ManyToManyField(blank=True, related_name='note_characters', to='core.character')),
                ('locations', models.ManyToManyField(blank=True, related_name='note_locations', to='core.location')),
                ('organizations', models.ManyToManyField(blank=True, related_name='note_organizations', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('involved_characters', models.ManyToManyField(related_name='event_characters', to='core.character')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('involved_organizations', models.ManyToManyField(related_name='event_organizations', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='organizations',
            field=models.ManyToManyField(related_name='character_organizations', to='core.organization'),
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.character')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.character',),
        ),
    ]
