# Generated by Django 4.2.11 on 2024-12-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.campaign'),
        ),
        migrations.AlterField(
            model_name='location',
            name='neighboring_locations',
            field=models.ManyToManyField(related_name='neighboring_locationsneighbors', to='core.location'),
        ),
    ]
