# Generated by Django 4.2.11 on 2024-12-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_location_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='hostility',
            field=models.TextField(choices=[('F', 'Friendly'), ('N', 'Neutral'), ('H', 'Hostile')], default='N'),
        ),
        migrations.AlterField(
            model_name='location',
            name='neighboring_locations',
            field=models.ManyToManyField(related_name='neighbors', to='core.location'),
        ),
    ]
