# Generated by Django 4.2.11 on 2024-12-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_location_hostility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='neighboring_locations',
            field=models.ManyToManyField(blank=True, related_name='neighbors', to='core.location'),
        ),
    ]
